In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import wget

In [2]:
pd.__version__

'2.1.4'

In [5]:
!pip install wget

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9680 sha256=32aa6ce7e210717210d5b1ce7e06ccbe8e1893186ea41efc26d5f22f0efc8640
  Stored in directory: c:\users\oluwapemiadekanmi\appdata\local\pip\cache\wheels\40\b3\0f\a40dbd1c6861731779f62cc4babcb234387e11d697df70ee97
Successfully built wget



[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"
wget.download(url, "car_fuel_efficiency.csv")

100% [............................................................................] 874188 / 874188

'car_fuel_efficiency (1).csv'

In [10]:
# !curl -L -o car_fuel_efficiency.csv https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv


In [15]:
df = pd.read_csv("car_fuel_efficiency.csv")


Question 2: Records count

In [16]:
df
# record count = 9704

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

Question 3: Fuel Types


In [18]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

Question 4: Missing Values

In [19]:
df.isnull().sum()
# columns with missing values = 4

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

Question 5: Max Fuel Efficiency


In [24]:
# maximun fuel efficiency of cars from Asia
asia_cars = df[df['origin'] == 'Asia']
asia_max_efficiency = asia_cars["fuel_efficiency_mpg"].max()
print("Maximum fuel efficiency of cars from Asia:", asia_max_efficiency)

Maximum fuel efficiency of cars from Asia: 23.759122836520497


Question 6: Median Value of Horsepower

In [27]:
# median value of horsepower column
horsepower_median = df['horsepower'].median()
print('Median value for horsepower:', horsepower_median)

Median value for horsepower: 149.0


In [30]:
# most frequent value of horsepower column
horsepower_mode = df['horsepower'].mode()[0]
print('Mode value for horsepower:', horsepower_mode)

Mode value for horsepower: 152.0


In [46]:
# filling the missing values with the mode value
df['horsepower'] = df['horsepower'].fillna(horsepower_mode)
df['horsepower']

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [52]:
# calculate th median again to see changes
horsepower_median = df['horsepower'].median()
horsepower_median

print("Median value:", horsepower_median, "It increased")

Median value: 152.0 It increased


Question 7: Sum of weights

In [54]:
# select all cars from asia
asia_cars = df[df["origin"] == "Asia"]
asia_cars.head(10)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   
34                  150            2.0       149.0     2844.227534   
38                  190            5.0       158.0     3761.994038   
43                  170            4.0       123.0     2957.681110   
44                  240            2.0       142.0     2544.516802   
48                  190            5.0       202.0     2531.185247   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
34          17.3        2014   Asia    Diesel  Front-wheel drive        0.0   
38           NaN        2019   Asia  Gasoline  Front-wheel drive        1.0   
43          14.4        2012   Asia    Diesel    All-wheel drive       -1.0   
44          12.9        2016   Asia  Gasoline    All-wheel drive        0.0   
48          16.2        2016   Asia  Gasoline    All-wheel drive        0.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730  
34            15.353788  
38            11.645724  
43            15.039797  
44            17.600328  
48            17.983505

In [56]:
# Select only columns vehicle_weight and model_year
subset = df[["vehicle_weight", "model_year"]]
subset.head(7)

vehicle_weight  model_year
0     3413.433759        2003
1     3149.664934        2007
2     3079.038997        2018
3     2542.392402        2009
4     3460.870990        2009
5     2484.883986        2008
6     3006.542287        2012

In [70]:
# Get the underlying NumPy array. Let's call it X
X = df[["vehicle_weight", "model_year"]].to_numpy()[:7]
X

array([[3413.43375861, 2003.        ],
       [3149.66493422, 2007.        ],
       [3079.03899737, 2018.        ],
       [2542.39240183, 2009.        ],
       [3460.87098999, 2009.        ],
       [2484.88398604, 2008.        ],
       [3006.54228722, 2012.        ]])

In [71]:
# matirx multiplication
XTX = X.T.dot(X)
XTX

array([[64707732.45267163, 42471352.31816066],
       [42471352.31816066, 28264752.        ]])

In [72]:
# Inverse
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 1.12464107e-06, -1.68991495e-06],
       [-1.68991495e-06,  2.57468996e-06]])

In [73]:
# create an array with y values
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [74]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv.dot(X.T).dot(y)
w

array([0.07099685, 0.41931263])

In [75]:
# sum of all elements
w.sum()

0.4903094879707467

In [76]:
print('sum approximately:', 0.5)

sum approximately: 0.5
